# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            RoRiH.com
tagline:          Black Theme for Jekyll
description:      "A toy website."
url:              index.html
baseurl:          /
collections_dir:  content

collections:
  intros:
    output: true
    order:
      - b.md 
      - a.md
  mathpages:
    output: true
    sort_by: lesson

author:
  name:           Robert Holmes
  url:            

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            

github:
  repo:             
