# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            RoRiH.com
tagline:          
description:      "Welcome to the Rileypedia."
url:              index.html
baseurl:          /

collections_dir:  content
collections:
  intros:
    output: true
    order: 
      - b.md
      - a.md

  mathpages:
    output: true
    nav_label: COUNTING LESSONS
    sort_by: lesson

defaults:
  - scope:
      path: ""
      type: "intros"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "mathpages"
    values:
      layout: "page"

author:
  name:           Robert Holmes
  url:            

paginate:         5
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-gist
  - jekyll-paginate
