# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            RoRiH.com
tagline:          
description:      "Welcome to the Rileypedia."
url:              index.html
baseurl:          /

collections_dir:  content
collections:
  about:
    output: true
    order: 
      - a.md

  topos:
    output: true
    nav_label: CATEGORY & TOPOS
    sort_by: lesson

  counting:
    output: true
    nav_label: COUNTING
    sort_by: lesson

defaults:
  - scope:
      path: ""
      type: "about"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "counting"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "topos"
    values:
      layout: "page"

author:
  name:           Robert Holmes
  url:            

paginate:         5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
